name: define dependent jobs
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ secrets.username }}
      GITHUB_PASSWORD: ${{ github.token }}
      GITHUB_EMAIL: ${{ secrets.email }}
    steps:
      - name: Checkout working branch
        uses: actions/checkout@v2
      - name: Build the binary
        run: |
          git remote set-url origin https://.:$GITHUB_PASSWORD@github.com/AxiomSamarth/github-actions-101
          echo "github.com:\n- user: $GITHUB_USER\n  oauth_token: $GITHUB_PASSWORD\n  protocol: https" > ~/.config/hub
          chmod go-r ~/.config/hub
          
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name $GITHUB_USER

          git checkout -b create-binary

          go build main.go
          chmod +x ./main

          git add ./main
          git commit -m "Added binary executable of main"
          git push origin create-binary

          hub pull-request --base main --head create-binary -F- <<< "Added binary executable of main"


