name: define dependent jobs
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout working branch
        uses: actions/checkout@v2
      - name: Build the binary
        run: |
          git checkout -b create-binary

          go build main.go
          chmod +x ./main

          git add ./main
          git commit -m "Added binary executable of main"
          git push origin create-binary

          hub pull-request --base main --head create-binary -F- <<< "Added binary executable of main"


