name: define dependent jobs
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout working branch
        uses: actions/checkout@v2
      - name: run-test
        run: go test
  create-bin:
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - name: build the binary
        run: go build main.go