name: define dependent jobs
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the working branch
        uses: actions/checkout@v2
      - name: Setup-go
        uses: actions/setup-go@v2
      - name: Create the binary & execute
        run: |
          git checkout -b create-binary
          go build main.go
          chmod +x ./main
          ./main

          git push origin create-binary


