name: define dependent jobs
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the working branch
        uses: actions/checkout@v2
      - name: Setup-go
        uses: actions/setup-go@v2
      - name: Run test
        run: go test
  create-binary:
    runs-on: ubuntu-latest
    needs: run-test
    steps:
      - name: Checkout the working branch
        uses: actions/checkout@v2
      - name: Setup-go
        uses: actions/setup-go@v2
      - name: Create the binary & execute
        run: |
          go build main.go
          chmod +x ./main
          ./main
