name: upload-log-file
on: push
jobs:
  upload-log-file:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13' ]
    steps:
      - name: Checkout the current working branch
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run the tests
        run: go test