name: define dependent jobs
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the working branch
        uses: actions/checkout@v2
      - name: setup-go
        uses: actions/setup-go@v2
      - name: run the test
        run: go test
  create-binary:
    runs-on: ubuntu-latest
    needs: run-test
    steps:
      - name: checkout the working branch
        uses: actions/checkout@v2
      - name: setup-go
        uses: actions/setup-go@v2
      - name: create binary & execute
        run: |
          go build main.go
          chmod +x ./main.go
          ./main
