name: upload-log-file
on: push
jobs:
  upload-log-file:
    runs-on: ubuntu-latest
    steps:
      - name: generate log file
        run: |
          echo "this is the log file of failed test script" > output.log
      - name: upload log file as artifact
        uses: actions/upload-artifact@v2
        with:
          path: output.log # the name of the artifact will be defaulted to 'artifact'
          if-no-files-found: error # 'ignore' label can also be used