name: upload-log-file
on: push
jobs:
  upload-log-file:
    runs-on: ubuntu-latest
    steps:
      - name: upload log file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: output-first.log
          if-no-files-found: error # 'ignore' label can also be used